//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrialManager.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrialManager.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Draw.
        /// </summary>
        public static string Command_CreateDraw {
            get {
                return ResourceManager.GetString("Command_CreateDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Command_ExportDraw {
            get {
                return ResourceManager.GetString("Command_ExportDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import New Data.
        /// </summary>
        public static string Command_ImportData {
            get {
                return ResourceManager.GetString("Command_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Draw.
        /// </summary>
        public static string Command_PrintDraw {
            get {
                return ResourceManager.GetString("Command_PrintDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Command_ViewDocumentation {
            get {
                return ResourceManager.GetString("Command_ViewDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Header_Address {
            get {
                return ResourceManager.GetString("Header_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        public static string Header_Dog {
            get {
                return ResourceManager.GetString("Header_Dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dogs.
        /// </summary>
        public static string Header_DogList {
            get {
                return ResourceManager.GetString("Header_DogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trialist Entry.
        /// </summary>
        public static string Header_EditTrialist {
            get {
                return ResourceManager.GetString("Header_EditTrialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Header_Email {
            get {
                return ResourceManager.GetString("Header_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor.
        /// </summary>
        public static string Header_FullName {
            get {
                return ResourceManager.GetString("Header_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Header_PhoneNumber {
            get {
                return ResourceManager.GetString("Header_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Header_RunDay {
            get {
                return ResourceManager.GetString("Header_RunDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Number.
        /// </summary>
        public static string Header_RunNumber {
            get {
                return ResourceManager.GetString("Header_RunNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Data File.
        /// </summary>
        public static string Header_SelectDataFile {
            get {
                return ResourceManager.GetString("Header_SelectDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Header_Status {
            get {
                return ResourceManager.GetString("Header_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: Right-click an entry to edit it!.
        /// </summary>
        public static string Hint_RightClickToEdit {
            get {
                return ResourceManager.GetString("Hint_RightClickToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs Per Day.
        /// </summary>
        public static string Hint_RunsPerDay {
            get {
                return ResourceManager.GetString("Hint_RunsPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        public static string Hint_SearchTrialists {
            get {
                return ResourceManager.GetString("Hint_SearchTrialists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Trial Location.
        /// </summary>
        public static string Hint_TrialLocation {
            get {
                return ResourceManager.GetString("Hint_TrialLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Name.
        /// </summary>
        public static string Hint_TrialName {
            get {
                return ResourceManager.GetString("Hint_TrialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Notes.
        /// </summary>
        public static string Hint_TrialNotes {
            get {
                return ResourceManager.GetString("Hint_TrialNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        public static string Hint_TrialStartDate {
            get {
                return ResourceManager.GetString("Hint_TrialStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Start Time.
        /// </summary>
        public static string Hint_TrialStartTime {
            get {
                return ResourceManager.GetString("Hint_TrialStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Label_Done {
            get {
                return ResourceManager.GetString("Label_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string Label_ImportData {
            get {
                return ResourceManager.GetString("Label_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Stepper_Continue {
            get {
                return ResourceManager.GetString("Stepper_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entry.
        /// </summary>
        public static string ToolTip_AddItem {
            get {
                return ResourceManager.GetString("ToolTip_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entry.
        /// </summary>
        public static string ToolTip_DeleteItem {
            get {
                return ResourceManager.GetString("ToolTip_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Entry.
        /// </summary>
        public static string ToolTip_EditItem {
            get {
                return ResourceManager.GetString("ToolTip_EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to edit entry.
        /// </summary>
        public static string ToolTip_EditRightClickShortcutHint {
            get {
                return ResourceManager.GetString("ToolTip_EditRightClickShortcutHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View TrialManager&apos;s documentation.
        /// </summary>
        public static string ToolTip_ViewDocumentation {
            get {
                return ResourceManager.GetString("ToolTip_ViewDocumentation", resourceCulture);
            }
        }
    }
}
