//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrialManager.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Carl Stephens 2020.
        /// </summary>
        public static string App_Copyright {
            get {
                return ResourceManager.GetString("App_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrialManager.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string App_VersionIdentifier {
            get {
                return ResourceManager.GetString("App_VersionIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Command_AboutApp {
            get {
                return ResourceManager.GetString("Command_AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Command_Close {
            get {
                return ResourceManager.GetString("Command_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Draw.
        /// </summary>
        public static string Command_CreateDraw {
            get {
                return ResourceManager.GetString("Command_CreateDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Command_ExportDraw {
            get {
                return ResourceManager.GetString("Command_ExportDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import New Data.
        /// </summary>
        public static string Command_ImportData {
            get {
                return ResourceManager.GetString("Command_ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Draw.
        /// </summary>
        public static string Command_PrintDraw {
            get {
                return ResourceManager.GetString("Command_PrintDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Command_ViewDocumentation {
            get {
                return ResourceManager.GetString("Command_ViewDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Header_Address {
            get {
                return ResourceManager.GetString("Header_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        public static string Header_Dog {
            get {
                return ResourceManager.GetString("Header_Dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor.
        /// </summary>
        public static string Header_FullName {
            get {
                return ResourceManager.GetString("Header_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Header_RunDay {
            get {
                return ResourceManager.GetString("Header_RunDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Number.
        /// </summary>
        public static string Header_RunNumber {
            get {
                return ResourceManager.GetString("Header_RunNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Data File.
        /// </summary>
        public static string Header_SelectDataFile {
            get {
                return ResourceManager.GetString("Header_SelectDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Header_Status {
            get {
                return ResourceManager.GetString("Header_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Trial Location.
        /// </summary>
        public static string Hint_TrialLocation {
            get {
                return ResourceManager.GetString("Hint_TrialLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Stepper_Continue {
            get {
                return ResourceManager.GetString("Stepper_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View TrialManager&apos;s documentation.
        /// </summary>
        public static string ToolTip_ViewDocumentation {
            get {
                return ResourceManager.GetString("ToolTip_ViewDocumentation", resourceCulture);
            }
        }
    }
}
