// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialManager.Core.Model.TrialistDb;

namespace TrialManager.Core.Migrations
{
    [DbContext(typeof(TrialistContext))]
    [Migration("20190805023726_Add location and address fields to Trialist")]
    partial class AddlocationandaddressfieldstoTrialist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("TrialManager.Core.Model.TrialistDb.Trialist", b =>
                {
                    b.Property<int>("TrialistId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<byte[]>("Dogs")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<byte[]>("Location")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("Status");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("TrialistId");

                    b.ToTable("Trialists");
                });
#pragma warning restore 612, 618
        }
    }
}
