// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialManager.Core.Model.Context;

namespace TrialManager.Core.Migrations
{
    [DbContext(typeof(ManagerContext))]
    [Migration("20190726001501_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("TrialManager.Core.Model.ContextModel.Trialist", b =>
                {
                    b.Property<int>("TrialistId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Dogs")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("Status");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("TrialistId");

                    b.ToTable("Trialists");
                });
#pragma warning restore 612, 618
        }
    }
}
