// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialManager.Core.Model.Context;

namespace TrialManager.Core.Migrations
{
    [DbContext(typeof(ManagerContext))]
    partial class ManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("UIConcepts.Core.Model.ContextModel.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<int?>("TrialistId");

                    b.HasKey("DogId");

                    b.HasIndex("TrialistId");

                    b.ToTable("Dog");
                });

            modelBuilder.Entity("UIConcepts.Core.Model.ContextModel.Trialist", b =>
                {
                    b.Property<int>("TrialistId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("Status");

                    b.Property<string>("Surname");

                    b.HasKey("TrialistId");

                    b.ToTable("Trialists");
                });

            modelBuilder.Entity("UIConcepts.Core.Model.ContextModel.Dog", b =>
                {
                    b.HasOne("UIConcepts.Core.Model.ContextModel.Trialist")
                        .WithMany("Dogs")
                        .HasForeignKey("TrialistId");
                });
#pragma warning restore 612, 618
        }
    }
}
