// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialManager.Core.Model.TrialistDb;

namespace TrialManager.Core.Migrations
{
    [DbContext(typeof(TrialistContext))]
    partial class TrialistContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TrialManager.Core.Model.TrialistDb.Trialist", b =>
                {
                    b.Property<int>("TrialistId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<byte[]>("Dogs")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<byte[]>("Location")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.Property<DateTime>("PreferredDay");

                    b.Property<int>("Status");

                    b.Property<int?>("TravellingPartnerTrialistId");

                    b.HasKey("TrialistId");

                    b.HasIndex("TravellingPartnerTrialistId");

                    b.ToTable("Trialists");
                });

            modelBuilder.Entity("TrialManager.Core.Model.TrialistDb.Trialist", b =>
                {
                    b.HasOne("TrialManager.Core.Model.TrialistDb.Trialist", "TravellingPartner")
                        .WithMany()
                        .HasForeignKey("TravellingPartnerTrialistId");
                });
#pragma warning restore 612, 618
        }
    }
}
